### ISSUE TITLE
Multiprocessing fails on newer OS releases for Mac and Windows

### ISSUE THREAD

**Issue by TrystanScottLambert** [TrystanScottLambert/pyFoF#52]
running the Experiment class crashes with the following error. I think it's due to parralization. 

runfile('/Users/wvankempen/Documents/PhD/KiDS/Code/FoF.py', wdir='/Users/wvankempen/Documents/PhD/KiDS/Code')

 

 

raceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/opt/anaconda3/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main

    exitcode = _main(fd, parent_sentinel)

  File "/opt/anaconda3/lib/python3.10/multiprocessing/spawn.py", line 125, in _main

    prepare(preparation_data)

  File "/opt/anaconda3/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare

    _fixup_main_from_path(data['init_main_from_path'])

  File "/opt/anaconda3/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path

    main_content = runpy.run_path(main_path,

  File "/opt/anaconda3/lib/python3.10/runpy.py", line 269, in run_path

    return _run_module_code(code, init_globals, run_name,

  File "/opt/anaconda3/lib/python3.10/runpy.py", line 96, in _run_module_code

    _run_code(code, mod_globals, init_globals,

  File "/opt/anaconda3/lib/python3.10/runpy.py", line 86, in _run_code

    exec(code, run_globals)

  File "/Users/wvankempen/Documents/PhD/KiDS/Code/FoF.py", line 26, in <module>

    run = pyFoF.experiment.Experiment(

  File "/opt/anaconda3/lib/python3.10/site-packages/pyFoF/experiment.py", line 41, in __init__

    members = self.run()

  File "/opt/anaconda3/lib/python3.10/site-packages/pyFoF/experiment.py", line 69, in run

    with multiprocessing.Manager() as manager:

  File "/opt/anaconda3/lib/python3.10/multiprocessing/context.py", line 57, in Manager

    m.start()

  File "/opt/anaconda3/lib/python3.10/multiprocessing/managers.py", line 562, in start

    self._process.start()

  File "/opt/anaconda3/lib/python3.10/multiprocessing/process.py", line 121, in start

    self._popen = self._Popen(self)

  File "/opt/anaconda3/lib/python3.10/multiprocessing/context.py", line 284, in _Popen

    return Popen(process_obj)

  File "/opt/anaconda3/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__

    super().__init__(process_obj)

  File "/opt/anaconda3/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__

    self._launch(process_obj)

  File "/opt/anaconda3/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch

    prep_data = spawn.get_preparation_data(process_obj._name)

  File "/opt/anaconda3/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data

    _check_not_importing_main()

  File "/opt/anaconda3/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main

    raise RuntimeError('''

RuntimeError:

        An attempt has been made to start a new process before the

        current process has finished its bootstrapping phase.

 

        This probably means that you are not using fork to start your

        child processes and you have forgotten to use the proper idiom

        in the main module:

 

            if __name__ == '__main__':

                freeze_support()

                ...

 

        The "freeze_support()" line can be omitted if the program

        is not going to be frozen to produce an executable.

Traceback (most recent call last):

 

  File "/opt/anaconda3/lib/python3.10/site-packages/spyder_kernels/py3compat.py", line 356, in compat_exec

    exec(code, globals, locals)

 

  File "/Users/wvankempen/Documents/PhD/KiDS/Code/FoF.py", line 26, in <module>

    run = pyFoF.experiment.Experiment(

 

  File "/opt/anaconda3/lib/python3.10/site-packages/pyFoF/experiment.py", line 41, in __init__

    members = self.run()

 

  File "/opt/anaconda3/lib/python3.10/site-packages/pyFoF/experiment.py", line 69, in run

    with multiprocessing.Manager() as manager:

 

  File "/opt/anaconda3/lib/python3.10/multiprocessing/context.py", line 57, in Manager

    m.start()

 

  File "/opt/anaconda3/lib/python3.10/multiprocessing/managers.py", line 566, in start

    self._address = reader.recv()

 

  File "/opt/anaconda3/lib/python3.10/multiprocessing/connection.py", line 255, in recv

    buf = self._recv_bytes()

 

  File "/opt/anaconda3/lib/python3.10/multiprocessing/connection.py", line 419, in _recv_bytes

    buf = self._recv(4)

 

  File "/opt/anaconda3/lib/python3.10/multiprocessing/connection.py", line 388, in _recv

    raise EOFError

 

EOFError

**Comment by TrystanScottLambert** [comment]
@BrutishGuy fix was to run `multiprocessing.set_start_method('fork')` So maybe we just need to include this in our own code and maybe put a warning to newer OS that this is happeing. Can you confirm that's ok?

**Comment by BrutishGuy** [comment]
@TrystanScottLambert yes, this seems to be case. After some digging around, this StackOverflow page describes the issue and seems to be solution as you say.

This is due to newer versions of Mac migrating away from 'fork' as the default process creation method towards 'spawn' as the default. Will probably need to also investigate if the 'fork' method will ever be deprecated at some point in future. In general, this fix also ensures multiprocessing also works for Windows.

**Comment by BrutishGuy** [comment]
In future a suggestion for bug-related issues to improve reproducibility would be to post things like OS version and type, Python version, and some steps to reproduce if applicable - this was a trivial case but in future we may run into more complex bugs and might be tough to reproduce generally without other details or sample data to test on.

**Comment by TrystanScottLambert** [comment]
@BrutishGuy ... k.

**Comment by TrystanScottLambert** [comment]
Fixed.
